# -*- coding: utf-8 -*-
"""Ses ile duygu tahmini yapan yapay zeka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeMzAasKpQZCoP65pz5Yg6a4kwjWcFqe
"""

# Gerekli kütüphaneleri kuralım
!pip install librosa numpy pandas matplotlib seaborn scikit-learn tensorflow

# Kaggle'dan veri çekmek için pratik bir kütüphane
!pip install opendatasets

!pip install resampy

import opendatasets as od
# TESS Veri setini indiriyoruz
od.download("https://www.kaggle.com/datasets/ejlok1/toronto-emotional-speech-set-tess")

import os
import librosa
import numpy as np
import pandas as pd

# Ses dosyasından özellik çıkaran fonksiyon
def özellik_cikar(dosya_yolu):
    audio, sample_rate = librosa.load(dosya_yolu, res_type='kaiser_fast')
    # MFCC: Sesin parmak izini çıkarır (40 adet özellik)
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    return mfccs_scaled_features

# Dosyaları okuma döngüsü
data = []
klasör_yolu = "/content/toronto-emotional-speech-set-tess/TESS-Toronto-emotional-speech-set-data"

for dizin, alt_dizinler, dosyalar in os.walk(klasör_yolu):
    for dosya in dosyalar:
        if dosya.endswith(".wav"):
            # Dosya isminden duyguyu yakala (Örn: OAF_back_fear.wav -> fear)
            # TESS veri setinde duygu genelde dosya isminin sonundadır.
            duygu = dosya.split('_')[-1].split('.')[0]

            dosya_tam_yolu = os.path.join(dizin, dosya)
            data_ozellikleri = özellik_cikar(dosya_tam_yolu)
            data.append([data_ozellikleri, duygu])

# Veriyi tabloya çevir
df = pd.DataFrame(data, columns=['Ozellikler', 'Duygu_Etiketi'])
print("İşlem tamam! Toplam ses sayısı:", len(df))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# X (Giriş verisi) ve y (Etiketler) ayırımı
X = np.array(df['Ozellikler'].tolist())
y = np.array(df['Duygu_Etiketi'].tolist())

# Etiketleri kodla (Angry -> 0, Happy -> 1...)
le = LabelEncoder()
y = to_categorical(le.fit_transform(y))

# Eğitim ve Test seti ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CNN Modeli için veriyi boyutlandırma (3D istiyor: Adet, Özellik, 1)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Model Mimarisi (Bu kısmı raporunda detaylı anlatacaksın)
model = Sequential()
model.add(Conv1D(64, kernel_size=5, activation='relu', input_shape=(40, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.3)) # Ezberlemeyi önler
model.add(Dense(y.shape[1], activation='softmax')) # Çıkış katmanı

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

# Eğitimi başlat
history = model.fit(X_train, y_train, batch_size=32, epochs=50, validation_data=(X_test, y_test))

# Başarıyı grafiğe dök (Raporun için çok önemli!)
import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Eğitim Başarısı')
plt.plot(history.history['val_accuracy'], label='Test Başarısı')
plt.legend()
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Veriyi Random Forest için uygun hale getirelim (3D -> 2D)
# CNN için (Adet, 40, 1) yapmıştık, şimdi (Adet, 40) yapıyoruz.
X_train_rf = X_train.reshape(X_train.shape[0], -1)
X_test_rf = X_test.reshape(X_test.shape[0], -1)

# 2. Random Forest Modelini Tanımla ve Eğit
# (n_estimators=100 demek, 100 tane karar ağacı kullan demek)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_rf, y_train)

# 3. Tahmin Yap ve Sonucu Hesapla
rf_tahminler = rf_model.predict(X_test_rf)

# CNN çıktıları 'olasılık' (softmax) formatındaydı, RF direkt sınıf verir.
# Kıyaslama için formatları eşitlememiz gerekebilir ama
# sklearn'in accuracy_score'u akıllıdır, halleder.
# Ancak y_test "one-hot" formatında (örn: [0, 0, 1, 0]),
# bunu normal sayıya (örn: 2) çevirelim:
import numpy as np
y_test_sayisal = np.argmax(y_test, axis=1)
rf_tahminler_sayisal = np.argmax(rf_tahminler, axis=1)

rf_basari = accuracy_score(y_test_sayisal, rf_tahminler_sayisal)

print(f"Random Forest Başarı Oranı: %{rf_basari * 100:.2f}")
print("\nDetaylı Rapor:\n")
print(classification_report(y_test_sayisal, rf_tahminler_sayisal))

import matplotlib.pyplot as plt

# CNN başarısını model.evaluate ile alalım
cnn_sonuc = model.evaluate(X_test, y_test, verbose=0)
cnn_basari = cnn_sonuc[1] # [loss, accuracy] döner, biz accuracy alıyoruz

# Verileri hazırla
modeller = ['Geleneksel (Random Forest)', 'Derin Öğrenme (CNN)']
basarilar = [rf_basari, cnn_basari]
renkler = ['orange', 'green']

# Çubuk grafiği çiz
plt.figure(figsize=(8, 5))
plt.bar(modeller, basarilar, color=renkler)
plt.ylabel('Doğruluk (Accuracy)')
plt.title('Algoritma Karşılaştırması')
plt.ylim(0, 1) # 0 ile 1 arası skala

# Çubukların üzerine oranları yaz
for i, v in enumerate(basarilar):
    plt.text(i, v + 0.01, f"%{v*100:.1f}", ha='center', fontweight='bold')

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# 1. Modelden tahminleri al
y_tahmin_olasiliklari = model.predict(X_test)
y_tahmin_siniflari = np.argmax(y_tahmin_olasiliklari, axis=1)

# 2. Gerçek etiketleri (One-Hot formatından) normal sayıya çevir
y_gercek_siniflari = np.argmax(y_test, axis=1)

# 3. Matrisi hesapla
cm = confusion_matrix(y_gercek_siniflari, y_tahmin_siniflari)

# 4. Şık bir grafik çiz (Seaborn Heatmap)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, # Duygu isimlerini eksenlere yazar
            yticklabels=le.classes_)

plt.title('Karmaşıklık Matrisi (Confusion Matrix)')
plt.ylabel('Gerçek Duygu')
plt.xlabel('Tahmin Edilen Duygu')
plt.show()